name = "kitcraft2"
author = "fluxd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03e2b1cf852d3215fa5a792ccd42e8fa71b5e1784f1a347584c30f4d509d3c6f"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
