name = "KITPack"
author = "fluxd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33f91a9cce37393ef2dd9dbc1d07c9a770234ad614e59615d75df7f3ad18d0df"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
