name = "KITPack"
author = "fluxd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92c328be97a7a1312b80a362fc4ad1697999372fa939a9d7ae8dcfa8cefedd52"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
